AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/*.rb'
    - 'spec/support/*.rb'
    - 'test/*.rb'

Lint/Loop:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/MethodLength:
  Max: 25

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
